def menuPrincipal ():
    print()
    print("\033[1;31;4m MENU DE INTERACCIÓN DEL CONTRATO \033[m ")
    print()
    print("\033[1mElige que operación quieres reallizar:\033[m ")
    print()
    print("1. Dar de alta un pretamista.")
    print("2. Dar de alta un cliente.")
    print("3. Depositar Garantía.")
    print("4. Solicitar un prestamo.")
    print("5. Aprobar un prestamo")
    print("6. Reembolsar un prestamo")
    print("7. Liquidar Garantia")
    print("8. Obtener prestamos del cliente")
    print("9. Obtener detalles del prestamo")
    print("0. Salir")
    print()